package by.yachnikzakhar.newsmanagement.controller;

public enum CommandName {
    SIGN_IN, REGISTRATION, GO_TO_REGISTRATION,
    GO_TO_SIGN_IN, GO_TO_ADD_NEWS, SHOW_NEWS, CHANGE_NEWS,
    DELETE_NEWS, LOGOUT, GO_TO_ADMINISTRATION, GO_TO_MAIN_PAGE,
    GO_TO_CHANGE_NEWS, ADD_NEWS, CHANGE_LOCALE, GO_TO_ERROR_PAGE,
    BLOCK_USER, ADD_USER_ADMIN_ROLE, REMOVE_USER_ADMIN_ROLE;
}
