package by.yachnikzakhar.newsmanagement.controller;

public enum CommandName {
    SIGN_IN, REGISTRATION, GO_TO_REGISTRATION, WELCOME,
    GO_TO_SIGN_IN, GO_TO_ADD_NEWS, SHOW_NEWS, CHANGE_NEWS,
    DELETE_NEWS, LOGOUT, GO_TO_ADMINISTRATION, GO_TO_MAIN_PAGE_AFTER_SIGN_IN;
}
